### ISSUE TITLE
how to apply workload partitioning using this appliance

### ISSUE THREAD

**Issue by wzhu2x** [openshift/appliance#135]
As I know Workload partitioning can only be enabled during cluster installation, So How should I configure to enable this feature when using the appliance to install the cluster

**Comment by danielerez** [comment]
You can give it a try by including a cluster-manifest with storage configuration inside the config-image.
I.e. follow this [doucoment](https://github.com/openshift/assisted-service/blob/master/docs/user-guide/install-customization.md#manifests-use-cases) for creating a MachineConfig of storage config with partitioning.
Then, when generating the [config-iso](https://github.com/openshift/appliance/blob/master/docs/user-guide.md#generate-a-cluster-configuration-image), add the yaml under 'openshift' dir. E.g. /home/test/cluster_config/openshift/10-masters-storage-config.yaml

**Comment by wzhu2x** [comment]
yes, It works ,thank you very much
